const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await hre.ethers.getSigners();
  console.log("Deploying with:", deployer.address);

  const balance = await deployer.provider.getBalance(deployer.address);
  console.log("Balance:", hre.ethers.formatEther(balance), "SOL");
  console.log("");

  // 1. Deploy GenmonRegistry
  console.log("1. Deploying GenmonRegistry...");
  const RegistryFactory = await hre.ethers.getContractFactory("GenmonRegistry");
  const registry = await RegistryFactory.deploy();
  await registry.waitForDeployment();
  const registryAddr = await registry.getAddress();
  console.log("   GenmonRegistry:", registryAddr);

  // 2. Deploy EvolutionEngine
  console.log("2. Deploying EvolutionEngine...");
  const EvoFactory = await hre.ethers.getContractFactory("EvolutionEngine");
  const evolution = await EvoFactory.deploy(registryAddr);
  await evolution.waitForDeployment();
  const evolutionAddr = await evolution.getAddress();
  console.log("   EvolutionEngine:", evolutionAddr);

  // 3. Deploy LaunchExecutor
  console.log("3. Deploying LaunchExecutor...");
  const LaunchFactory = await hre.ethers.getContractFactory("LaunchExecutor");
  const launcher = await LaunchFactory.deploy(registryAddr);
  await launcher.waitForDeployment();
  const launcherAddr = await launcher.getAddress();
  console.log("   LaunchExecutor:", launcherAddr);

  // 4. Deploy TreasuryManager
  console.log("4. Deploying TreasuryManager...");
  const TreasuryFactory = await hre.ethers.getContractFactory("TreasuryManager");
  const treasury = await TreasuryFactory.deploy();
  await treasury.waitForDeployment();
  const treasuryAddr = await treasury.getAddress();
  console.log("   TreasuryManager:", treasuryAddr);

  // Write addresses to frontend
  const content = [
    '// Contract addresses — Auto-generated by deploy script',
    '// ' + new Date().toISOString(),
    '// Tokens are launched via Pump.fun — no GENToken contract needed',
    '',
    'const ZERO = "0x0000000000000000000000000000000000000000" as `0x${string}`;',
    '',
    'export const TESTNET_ADDRESSES = {',
    '  GENMON_REGISTRY: "' + registryAddr + '" as `0x${string}`,',
    '  EVOLUTION_ENGINE: "' + evolutionAddr + '" as `0x${string}`,',
    '  LAUNCH_EXECUTOR: "' + launcherAddr + '" as `0x${string}`,',
    '  TREASURY_MANAGER: "' + treasuryAddr + '" as `0x${string}`,',
    '} as const;',
    '',
    'export const MAINNET_ADDRESSES = {',
    '  GENMON_REGISTRY: ZERO as `0x${string}`,',
    '  EVOLUTION_ENGINE: ZERO as `0x${string}`,',
    '  LAUNCH_EXECUTOR: ZERO as `0x${string}`,',
    '  TREASURY_MANAGER: ZERO as `0x${string}`,',
    '} as const;',
    '',
    'export function getContractAddresses(chainId: number) {',
    '  if (chainId === 143) return { addresses: MAINNET_ADDRESSES, deployed: false };',
    '  return { addresses: TESTNET_ADDRESSES, deployed: true };',
    '}',
    '',
    'export const CONTRACT_ADDRESSES = TESTNET_ADDRESSES;',
    'export const CONTRACTS_DEPLOYED = true;',
    '',
  ].join('\n');

  fs.writeFileSync(path.join(__dirname, "../src/contracts/addresses.ts"), content);

  console.log("");
  console.log("All contracts deployed!");
  console.log("Addresses written to src/contracts/addresses.ts");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});